{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "2.ipynb",
      "provenance": [],
      "collapsed_sections": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 3,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "RprBLnOGhpqS",
        "outputId": "bd385f9b-bf29-476f-f53e-0f7b7a37486c"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "HEURISTIC VALUES  : {'A': 1, 'B': 6, 'C': 2, 'D': 12, 'E': 2, 'F': 1, 'G': 5, 'H': 7, 'I': 7, 'J': 1, 'T': 3}\n",
            "SOLUTION GRAPH    : {}\n",
            "PROCESSING NODE   : A\n",
            "-------------------------------------------------------------\n",
            "HEURISTIC VALUES  : {'A': 10, 'B': 6, 'C': 2, 'D': 12, 'E': 2, 'F': 1, 'G': 5, 'H': 7, 'I': 7, 'J': 1, 'T': 3}\n",
            "SOLUTION GRAPH    : {}\n",
            "PROCESSING NODE   : B\n",
            "-------------------------------------------------------------\n",
            "HEURISTIC VALUES  : {'A': 10, 'B': 6, 'C': 2, 'D': 12, 'E': 2, 'F': 1, 'G': 5, 'H': 7, 'I': 7, 'J': 1, 'T': 3}\n",
            "SOLUTION GRAPH    : {}\n",
            "PROCESSING NODE   : A\n",
            "-------------------------------------------------------------\n",
            "HEURISTIC VALUES  : {'A': 10, 'B': 6, 'C': 2, 'D': 12, 'E': 2, 'F': 1, 'G': 5, 'H': 7, 'I': 7, 'J': 1, 'T': 3}\n",
            "SOLUTION GRAPH    : {}\n",
            "PROCESSING NODE   : G\n",
            "-------------------------------------------------------------\n",
            "HEURISTIC VALUES  : {'A': 10, 'B': 6, 'C': 2, 'D': 12, 'E': 2, 'F': 1, 'G': 8, 'H': 7, 'I': 7, 'J': 1, 'T': 3}\n",
            "SOLUTION GRAPH    : {}\n",
            "PROCESSING NODE   : B\n",
            "-------------------------------------------------------------\n",
            "HEURISTIC VALUES  : {'A': 10, 'B': 8, 'C': 2, 'D': 12, 'E': 2, 'F': 1, 'G': 8, 'H': 7, 'I': 7, 'J': 1, 'T': 3}\n",
            "SOLUTION GRAPH    : {}\n",
            "PROCESSING NODE   : A\n",
            "-------------------------------------------------------------\n",
            "HEURISTIC VALUES  : {'A': 12, 'B': 8, 'C': 2, 'D': 12, 'E': 2, 'F': 1, 'G': 8, 'H': 7, 'I': 7, 'J': 1, 'T': 3}\n",
            "SOLUTION GRAPH    : {}\n",
            "PROCESSING NODE   : I\n",
            "-------------------------------------------------------------\n",
            "HEURISTIC VALUES  : {'A': 12, 'B': 8, 'C': 2, 'D': 12, 'E': 2, 'F': 1, 'G': 8, 'H': 7, 'I': 0, 'J': 1, 'T': 3}\n",
            "SOLUTION GRAPH    : {'I': []}\n",
            "PROCESSING NODE   : G\n",
            "-------------------------------------------------------------\n",
            "HEURISTIC VALUES  : {'A': 12, 'B': 8, 'C': 2, 'D': 12, 'E': 2, 'F': 1, 'G': 1, 'H': 7, 'I': 0, 'J': 1, 'T': 3}\n",
            "SOLUTION GRAPH    : {'I': [], 'G': ['I']}\n",
            "PROCESSING NODE   : B\n",
            "-------------------------------------------------------------\n",
            "HEURISTIC VALUES  : {'A': 12, 'B': 2, 'C': 2, 'D': 12, 'E': 2, 'F': 1, 'G': 1, 'H': 7, 'I': 0, 'J': 1, 'T': 3}\n",
            "SOLUTION GRAPH    : {'I': [], 'G': ['I'], 'B': ['G']}\n",
            "PROCESSING NODE   : A\n",
            "-------------------------------------------------------------\n",
            "HEURISTIC VALUES  : {'A': 6, 'B': 2, 'C': 2, 'D': 12, 'E': 2, 'F': 1, 'G': 1, 'H': 7, 'I': 0, 'J': 1, 'T': 3}\n",
            "SOLUTION GRAPH    : {'I': [], 'G': ['I'], 'B': ['G']}\n",
            "PROCESSING NODE   : C\n",
            "-------------------------------------------------------------\n",
            "HEURISTIC VALUES  : {'A': 6, 'B': 2, 'C': 2, 'D': 12, 'E': 2, 'F': 1, 'G': 1, 'H': 7, 'I': 0, 'J': 1, 'T': 3}\n",
            "SOLUTION GRAPH    : {'I': [], 'G': ['I'], 'B': ['G']}\n",
            "PROCESSING NODE   : A\n",
            "-------------------------------------------------------------\n",
            "HEURISTIC VALUES  : {'A': 6, 'B': 2, 'C': 2, 'D': 12, 'E': 2, 'F': 1, 'G': 1, 'H': 7, 'I': 0, 'J': 1, 'T': 3}\n",
            "SOLUTION GRAPH    : {'I': [], 'G': ['I'], 'B': ['G']}\n",
            "PROCESSING NODE   : J\n",
            "-------------------------------------------------------------\n",
            "HEURISTIC VALUES  : {'A': 6, 'B': 2, 'C': 2, 'D': 12, 'E': 2, 'F': 1, 'G': 1, 'H': 7, 'I': 0, 'J': 0, 'T': 3}\n",
            "SOLUTION GRAPH    : {'I': [], 'G': ['I'], 'B': ['G'], 'J': []}\n",
            "PROCESSING NODE   : C\n",
            "-------------------------------------------------------------\n",
            "HEURISTIC VALUES  : {'A': 6, 'B': 2, 'C': 1, 'D': 12, 'E': 2, 'F': 1, 'G': 1, 'H': 7, 'I': 0, 'J': 0, 'T': 3}\n",
            "SOLUTION GRAPH    : {'I': [], 'G': ['I'], 'B': ['G'], 'J': [], 'C': ['J']}\n",
            "PROCESSING NODE   : A\n",
            "-------------------------------------------------------------\n",
            "FOR GRAPH SOLUTION, TRAVERSE THE GRAPH FROM THE START NODE: A\n",
            "------------------------------------------------------------\n",
            "{'I': [], 'G': ['I'], 'B': ['G'], 'J': [], 'C': ['J'], 'A': ['B', 'C']}\n",
            "------------------------------------------------------------\n",
            "HEURISTIC VALUES  : {'A': 1, 'B': 6, 'C': 12, 'D': 10, 'E': 4, 'F': 4, 'G': 5, 'H': 7}\n",
            "SOLUTION GRAPH    : {}\n",
            "PROCESSING NODE   : A\n",
            "-------------------------------------------------------------\n",
            "HEURISTIC VALUES  : {'A': 11, 'B': 6, 'C': 12, 'D': 10, 'E': 4, 'F': 4, 'G': 5, 'H': 7}\n",
            "SOLUTION GRAPH    : {}\n",
            "PROCESSING NODE   : D\n",
            "-------------------------------------------------------------\n",
            "HEURISTIC VALUES  : {'A': 11, 'B': 6, 'C': 12, 'D': 10, 'E': 4, 'F': 4, 'G': 5, 'H': 7}\n",
            "SOLUTION GRAPH    : {}\n",
            "PROCESSING NODE   : A\n",
            "-------------------------------------------------------------\n",
            "HEURISTIC VALUES  : {'A': 11, 'B': 6, 'C': 12, 'D': 10, 'E': 4, 'F': 4, 'G': 5, 'H': 7}\n",
            "SOLUTION GRAPH    : {}\n",
            "PROCESSING NODE   : E\n",
            "-------------------------------------------------------------\n",
            "HEURISTIC VALUES  : {'A': 11, 'B': 6, 'C': 12, 'D': 10, 'E': 0, 'F': 4, 'G': 5, 'H': 7}\n",
            "SOLUTION GRAPH    : {'E': []}\n",
            "PROCESSING NODE   : D\n",
            "-------------------------------------------------------------\n",
            "HEURISTIC VALUES  : {'A': 11, 'B': 6, 'C': 12, 'D': 6, 'E': 0, 'F': 4, 'G': 5, 'H': 7}\n",
            "SOLUTION GRAPH    : {'E': []}\n",
            "PROCESSING NODE   : A\n",
            "-------------------------------------------------------------\n",
            "HEURISTIC VALUES  : {'A': 7, 'B': 6, 'C': 12, 'D': 6, 'E': 0, 'F': 4, 'G': 5, 'H': 7}\n",
            "SOLUTION GRAPH    : {'E': []}\n",
            "PROCESSING NODE   : F\n",
            "-------------------------------------------------------------\n",
            "HEURISTIC VALUES  : {'A': 7, 'B': 6, 'C': 12, 'D': 6, 'E': 0, 'F': 0, 'G': 5, 'H': 7}\n",
            "SOLUTION GRAPH    : {'E': [], 'F': []}\n",
            "PROCESSING NODE   : D\n",
            "-------------------------------------------------------------\n",
            "HEURISTIC VALUES  : {'A': 7, 'B': 6, 'C': 12, 'D': 2, 'E': 0, 'F': 0, 'G': 5, 'H': 7}\n",
            "SOLUTION GRAPH    : {'E': [], 'F': [], 'D': ['E', 'F']}\n",
            "PROCESSING NODE   : A\n",
            "-------------------------------------------------------------\n",
            "FOR GRAPH SOLUTION, TRAVERSE THE GRAPH FROM THE START NODE: A\n",
            "------------------------------------------------------------\n",
            "{'E': [], 'F': [], 'D': ['E', 'F'], 'A': ['D']}\n",
            "------------------------------------------------------------\n"
          ]
        }
      ],
      "source": [
        "class Graph:\n",
        "    def __init__(self, graph, heuristicNodeList, startNode):  \n",
        "        self.graph = graph\n",
        "        self.H=heuristicNodeList\n",
        "        self.start=startNode\n",
        "        self.parent={}\n",
        "        self.status={}\n",
        "        self.solutionGraph={}\n",
        "    def applyAOStar(self):  \n",
        "        self.aoStar(self.start, False)\n",
        "\n",
        "    def getNeighbors(self, v):     \n",
        "        return self.graph.get(v,'')\n",
        "    def getStatus(self,v):     \n",
        "        return self.status.get(v,0)\n",
        "    def setStatus(self,v, val):    \n",
        "        self.status[v]=val\n",
        "    def getHeuristicNodeValue(self, n):\n",
        "        return self.H.get(n,0)     \n",
        "    def setHeuristicNodeValue(self, n, value):\n",
        "        self.H[n]=value            \n",
        "    def printSolution(self):\n",
        "        print(\"FOR GRAPH SOLUTION, TRAVERSE THE GRAPH FROM THE START NODE:\"\n",
        "        ,self.start)\n",
        "        print(\"------------------------------------------------------------\")\n",
        "        print(self.solutionGraph)\n",
        "        print(\"------------------------------------------------------------\")\n",
        "    \n",
        "    def computeMinimumCostChildNodes(self, v):      \n",
        "        minimumCost=0\n",
        "        costToChildNodeListDict={}\n",
        "        costToChildNodeListDict[minimumCost]=[]\n",
        "        flag=True\n",
        "        for nodeInfoTupleList in self.getNeighbors(v):  \n",
        "            cost=0\n",
        "            nodeList=[]\n",
        "            for c, weight in nodeInfoTupleList:\n",
        "                cost=cost+self.getHeuristicNodeValue(c)+weight\n",
        "                nodeList.append(c)\n",
        "            if flag==True:                       \n",
        "                minimumCost=cost\n",
        "                costToChildNodeListDict[minimumCost]=nodeList      \n",
        "                flag=False\n",
        "            else:                                  \n",
        "                if minimumCost>cost:\n",
        "                    minimumCost=cost\n",
        "                    costToChildNodeListDict[minimumCost]=nodeList \n",
        "        return minimumCost, costToChildNodeListDict[minimumCost]  \n",
        "    def aoStar(self, v, backTracking):   \n",
        "        print(\"HEURISTIC VALUES  :\", self.H)\n",
        "        print(\"SOLUTION GRAPH    :\", self.solutionGraph)\n",
        "        print(\"PROCESSING NODE   :\", v)\n",
        "        print(\"-------------------------------------------------------------\")\n",
        "        \n",
        "        if self.getStatus(v) >= 0:       \n",
        "            minimumCost, childNodeList = self.computeMinimumCostChildNodes(v)\n",
        "            self.setHeuristicNodeValue(v, minimumCost)\n",
        "            self.setStatus(v,len(childNodeList))\n",
        "            \n",
        "            solved=True                    \n",
        "            for childNode in childNodeList:\n",
        "                self.parent[childNode]=v\n",
        "                if self.getStatus(childNode)!=-1:\n",
        "                    solved=solved & False\n",
        "            if solved==True:   \n",
        "                self.setStatus(v,-1)    \n",
        "                self.solutionGraph[v]=childNodeList       \n",
        "            if v!=self.start:              \n",
        "                self.aoStar(self.parent[v], True) \n",
        "                \n",
        "            if backTracking==False:      \n",
        "                for childNode in childNodeList:   \n",
        "                    self.setStatus(childNode,0)   \n",
        "                    self.aoStar(childNode, False)                      \n",
        "h1 = {'A': 1, 'B': 6, 'C': 2, 'D': 12, 'E': 2,\n",
        "      'F': 1, 'G': 5, 'H': 7, 'I': 7, 'J': 1, 'T': 3}\n",
        "graph1 = {\n",
        "    'A': [[('B', 1), ('C', 1)], [('D', 1)]],\n",
        "    'B': [[('G', 1)], [('H', 1)]],\n",
        "    'C': [[('J', 1)]],\n",
        "    'D': [[('E', 1), ('F', 1)]],\n",
        "    'G': [[('I', 1)]]   \n",
        "}\n",
        "G1= Graph(graph1, h1, 'A')\n",
        "G1.applyAOStar() \n",
        "G1.printSolution()\n",
        "h2 = {'A': 1, 'B': 6, 'C': 12, 'D': 10, 'E': 4, 'F': 4, 'G': 5, 'H': 7}  \n",
        "graph2 = {            \n",
        "    'A': [[('B', 1), ('C', 1)], [('D', 1)]],     \n",
        "    'B': [[('G', 1)], [('H', 1)]],              \n",
        "    'D': [[('E', 1), ('F', 1)]]                 \n",
        "}\n",
        "G2 = Graph(graph2, h2, 'A')                       \n",
        "G2.applyAOStar()                                  \n",
        "G2.printSolution()                                \n"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        ""
      ],
      "metadata": {
        "id": "f6lHwBWvi8TI"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}